services:
  - type: web
    name: telebot-course-processor
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: PORT
        value: 8080
